### ISSUE TITLE
Share common settings accross account configs

### ISSUE THREAD

**Issue by codethief** [pimalaya/neverest#6]
First of all, thanks so much for this great tool!

Let me explain the rationale behind my feature request a bit: I would like to set the same aliases, permissions, etc. for some of my accounts, without having to duplicate the same settings for every one of those accounts in my config. More generally, it'd be good if settings could be inherited in a way, so that I could have a whole bunch of accounts for $HOST_A with shared $SETTINGS_A, and some more accounts for $HOST_B, $HOST_C with a different set of shared settings.

**Comment by soywod** [comment]
> First of all, thanks so much for this great tool!

Thanks, I really appreciate :pray: 



> I would like to set the same aliases, permissions, etc. for some of my accounts, without having to duplicate the same settings for every one of those accounts in my config.

I know that [`mbsync`](https://isync.sourceforge.io/mbsync.html) and [OfflineIMAP](https://www.offlineimap.org/) do propose such feature. You need to declare and configure sources, then you need to connect sources together. But I find this API so overwhelming. Most of people (including me) just need to sync accounts once. Hence the choice behind `left` and `right`.

That said I am not against such feature, as long as it does not interfere with the actual API that I find more straightforward, intuitive and simple.

The main issue I see is the amount of work needed to achieve the goal. I mean, a clean solution where deserialization works well and give decent error messages. It would be faster, I think, to use a template engine in order to build your Neverest config file. A good candidate could be mustache [[1](https://mustache.github.io/mustache.5.html)] [[2](https://mustache.github.io/)].

**Comment by codethief** [comment]
Thanks, complexity is indeed a good point! Once a basic solution has been implemented, the next guy might come around the corner with a more complicated use case, which requires introducing even more logic and more abstraction, and likely variables, and one day you wake up and your config language is Turing-complete. 😅 It really is a slippery slope and I understand if you don't want to go down that path. :) So I'll settle with templating for now. Thanks that you took the time to consider my request!

**Comment by soywod** [comment]
If you find a "satisfying-enough" solution, please consider adding it to the [FAQ](https://github.com/pimalaya/neverest#faq) so people with similar needs can use your solution!
